"""
Database service module for Supabase table interactions
Handles all CRUD operations for the trading application tables
"""
from typing import Dict, List, Optional, Any
from datetime import datetime
import numpy as np
import pandas as pd
from .config import get_supabase


def _make_json_serializable(obj):
    """Convert numpy/pandas types to native Python types for JSON serialization"""
    # Handle None first
    if obj is None:
        return None
    
    # Check for numpy scalar types (must check before dict/list)
    if isinstance(obj, np.generic):
        return obj.item()  # Convert numpy scalar to Python native type
    
    # Check specific numpy integer types
    if isinstance(obj, (np.integer, np.int64, np.int32, np.int16, np.int8)):
        return int(obj)
    
    # Check specific numpy float types
    if isinstance(obj, (np.floating, np.float64, np.float32, np.float16)):
        return float(obj)
    
    # Check for numpy bool_ (must check as numpy.generic subclass)
    if type(obj).__name__ == 'bool_' or isinstance(obj, np.bool_):
        return bool(obj)
    
    # Check for numpy array
    if isinstance(obj, np.ndarray):
        return obj.tolist()
    
    # Check for pandas types
    if isinstance(obj, pd.DataFrame):
        return obj.to_dict('records')
    if isinstance(obj, pd.Series):
        return obj.to_dict()
    if isinstance(obj, pd.Timestamp):
        return obj.isoformat()
    
    # Handle dictionaries (recursive)
    if isinstance(obj, dict):
        return {key: _make_json_serializable(value) for key, value in obj.items()}
    
    # Handle lists/tuples (recursive)
    if isinstance(obj, (list, tuple)):
        return [_make_json_serializable(item) for item in obj]
    
    # Handle datetime
    if isinstance(obj, datetime):
        return obj.isoformat()
    
    # For everything else, return as-is
    return obj


# ============================================================================
# LIST ALL DATABASE TABLES
# ============================================================================

def list_all_tables() -> List[Dict[str, str]]:
    """
    List all database tables used in the application
    Returns a list of table names with descriptions
    """
    tables = [
        {
            "name": "users",
            "description": "User accounts and authentication",
            "columns": ["id", "email", "role", "created_at"]
        },
        {
            "name": "trade_signals",
            "description": "Trading signals generated by the AI system",
            "columns": ["id", "symbol", "signal_type", "confidence", "details", "timestamp"]
        },
        {
            "name": "portfolio",
            "description": "User portfolio holdings and positions",
            "columns": ["id", "user_id", "symbol", "quantity", "avg_price", "pnl", "updated_at"]
        },
        {
            "name": "system_logs",
            "description": "System event logging and audit trail",
            "columns": ["id", "event", "details", "timestamp"]
        },
        {
            "name": "documents",
            "description": "Research documents and file storage",
            "columns": ["id", "symbol", "file_name", "file_content", "embedding_vector", "uploaded_at"]
        },
        {
            "name": "data_health",
            "description": "Data quality and health monitoring",
            "columns": ["symbol", "data_fetch_status", "last_updated", "health_score"]
        }
    ]
    return tables


# ============================================================================
# USERS TABLE OPERATIONS
# ============================================================================

def create_user(email: str, role: str = "user") -> Optional[Dict]:
    """Create a new user"""
    supabase = get_supabase()
    if not supabase:
        return None
    
    try:
        result = supabase.table("users").insert({
            "email": email,
            "role": role
        }).execute()
        return result.data[0] if result.data else None
    except Exception as e:
        print(f"Error creating user: {e}")
        return None


def get_user_by_email(email: str) -> Optional[Dict]:
    """Get user by email"""
    supabase = get_supabase()
    if not supabase:
        return None
    
    try:
        result = supabase.table("users").select("*").eq("email", email).execute()
        return result.data[0] if result.data else None
    except Exception as e:
        print(f"Error getting user: {e}")
        return None


def get_all_users() -> List[Dict]:
    """Get all users"""
    supabase = get_supabase()
    if not supabase:
        return []
    
    try:
        result = supabase.table("users").select("*").execute()
        return result.data if result.data else []
    except Exception as e:
        print(f"Error getting users: {e}")
        return []


# ============================================================================
# TRADE SIGNALS TABLE OPERATIONS
# ============================================================================

def create_trade_signal(
    symbol: str,
    signal_type: str,  # 'buy', 'sell', 'hold'
    confidence: float,
    details: Optional[Dict] = None
) -> Optional[Dict]:
    """Create a new trade signal"""
    supabase = get_supabase()
    if not supabase:
        raise ValueError("Supabase client not configured. Check SUPABASE_URL and SUPABASE_KEY environment variables.")
    
    try:
        # Convert numpy/pandas types to JSON-serializable types
        serializable_details = _make_json_serializable(details or {})
        
        payload = {
            "symbol": symbol.upper(),
            "signal_type": signal_type.lower(),
            "confidence": float(confidence),  # Ensure it's a Python float
            "details": serializable_details,
            "timestamp": datetime.now().isoformat()
        }
        result = supabase.table("trade_signals").insert(payload).execute()
        if result.data and len(result.data) > 0:
            return result.data[0]
        else:
            raise ValueError(f"Insert returned no data. Response: {result}")
    except Exception as e:
        print(f"Error creating trade signal: {e}")
        raise  # Re-raise to show actual error


def get_trade_signals(
    symbol: Optional[str] = None,
    signal_type: Optional[str] = None,
    limit: int = 100
) -> List[Dict]:
    """Get trade signals with optional filtering"""
    supabase = get_supabase()
    if not supabase:
        return []
    
    try:
        query = supabase.table("trade_signals").select("*")
        
        if symbol:
            query = query.eq("symbol", symbol.upper())
        if signal_type:
            query = query.eq("signal_type", signal_type.lower())
        
        query = query.order("timestamp", desc=True).limit(limit)
        result = query.execute()
        return result.data if result.data else []
    except Exception as e:
        print(f"Error getting trade signals: {e}")
        return []


def get_latest_signal(symbol: str) -> Optional[Dict]:
    """Get the latest trade signal for a symbol"""
    supabase = get_supabase()
    if not supabase:
        return None
    
    try:
        result = supabase.table("trade_signals")\
            .select("*")\
            .eq("symbol", symbol.upper())\
            .order("timestamp", desc=True)\
            .limit(1)\
            .execute()
        return result.data[0] if result.data else None
    except Exception as e:
        print(f"Error getting latest signal: {e}")
        return None


# ============================================================================
# PORTFOLIO TABLE OPERATIONS
# ============================================================================

def add_to_portfolio(
    user_id: str,
    symbol: str,
    quantity: float,
    avg_price: float
) -> Optional[Dict]:
    """Add or update a position in portfolio"""
    supabase = get_supabase()
    if not supabase:
        return None
    
    try:
        # Check if position exists
        existing = supabase.table("portfolio")\
            .select("*")\
            .eq("user_id", user_id)\
            .eq("symbol", symbol.upper())\
            .execute()
        
        payload = {
            "user_id": user_id,
            "symbol": symbol.upper(),
            "quantity": quantity,
            "avg_price": avg_price,
            "pnl": 0,  # Will be calculated later
            "updated_at": datetime.now().isoformat()
        }
        
        if existing.data:
            # Update existing position
            result = supabase.table("portfolio")\
                .update(payload)\
                .eq("user_id", user_id)\
                .eq("symbol", symbol.upper())\
                .execute()
        else:
            # Insert new position
            result = supabase.table("portfolio").insert(payload).execute()
        
        return result.data[0] if result.data else None
    except Exception as e:
        print(f"Error adding to portfolio: {e}")
        return None


def get_portfolio(user_id: str) -> List[Dict]:
    """Get all positions for a user"""
    supabase = get_supabase()
    if not supabase:
        return []
    
    try:
        result = supabase.table("portfolio")\
            .select("*")\
            .eq("user_id", user_id)\
            .execute()
        return result.data if result.data else []
    except Exception as e:
        print(f"Error getting portfolio: {e}")
        return []


def update_portfolio_pnl(user_id: str, symbol: str, current_price: float) -> bool:
    """Update P&L for a portfolio position"""
    supabase = get_supabase()
    if not supabase:
        return False
    
    try:
        # Get position
        position = supabase.table("portfolio")\
            .select("*")\
            .eq("user_id", user_id)\
            .eq("symbol", symbol.upper())\
            .execute()
        
        if not position.data:
            return False
        
        pos = position.data[0]
        avg_price = pos.get("avg_price", 0)
        quantity = pos.get("quantity", 0)
        
        # Calculate P&L
        pnl = (current_price - avg_price) * quantity
        
        # Update
        supabase.table("portfolio")\
            .update({
                "pnl": pnl,
                "updated_at": datetime.now().isoformat()
            })\
            .eq("user_id", user_id)\
            .eq("symbol", symbol.upper())\
            .execute()
        
        return True
    except Exception as e:
        print(f"Error updating portfolio P&L: {e}")
        return False


def remove_from_portfolio(user_id: str, symbol: str) -> bool:
    """Remove a position from portfolio"""
    supabase = get_supabase()
    if not supabase:
        return False
    
    try:
        supabase.table("portfolio")\
            .delete()\
            .eq("user_id", user_id)\
            .eq("symbol", symbol.upper())\
            .execute()
        return True
    except Exception as e:
        print(f"Error removing from portfolio: {e}")
        return False


# ============================================================================
# SYSTEM LOGS TABLE OPERATIONS
# ============================================================================

def log_event(event: str, details: Optional[Dict] = None) -> Optional[Dict]:
    """Log a system event"""
    supabase = get_supabase()
    if not supabase:
        raise ValueError("Supabase client not configured. Check SUPABASE_URL and SUPABASE_KEY environment variables.")
    
    try:
        # Convert numpy/pandas types to JSON-serializable types
        serializable_details = _make_json_serializable(details or {})
        
        payload = {
            "event": event,
            "details": serializable_details,
            "timestamp": datetime.now().isoformat()
        }
        result = supabase.table("system_logs").insert(payload).execute()
        if result.data and len(result.data) > 0:
            return result.data[0]
        else:
            raise ValueError(f"Insert returned no data. Response: {result}")
    except Exception as e:
        print(f"Error logging event '{event}': {e}")
        raise  # Re-raise to show actual error


def get_recent_logs(limit: int = 100) -> List[Dict]:
    """Get recent system logs"""
    supabase = get_supabase()
    if not supabase:
        return []
    
    try:
        result = supabase.table("system_logs")\
            .select("*")\
            .order("timestamp", desc=True)\
            .limit(limit)\
            .execute()
        return result.data if result.data else []
    except Exception as e:
        print(f"Error getting logs: {e}")
        return []


def get_logs_by_event(event: str, limit: int = 100) -> List[Dict]:
    """Get logs filtered by event type"""
    supabase = get_supabase()
    if not supabase:
        return []
    
    try:
        result = supabase.table("system_logs")\
            .select("*")\
            .eq("event", event)\
            .order("timestamp", desc=True)\
            .limit(limit)\
            .execute()
        return result.data if result.data else []
    except Exception as e:
        print(f"Error getting logs by event: {e}")
        return []


# ============================================================================
# DOCUMENTS TABLE OPERATIONS (if using 'documents' table name)
# ============================================================================

def get_documents(symbol: Optional[str] = None, limit: int = 100) -> List[Dict]:
    """Get documents, optionally filtered by symbol"""
    supabase = get_supabase()
    if not supabase:
        return []
    
    try:
        query = supabase.table("documents").select("*")
        
        if symbol:
            query = query.eq("symbol", symbol.upper())
        
        query = query.order("uploaded_at", desc=True).limit(limit)
        result = query.execute()
        return result.data if result.data else []
    except Exception as e:
        print(f"Error getting documents: {e}")
        return []


# ============================================================================
# DATA HEALTH TABLE OPERATIONS
# ============================================================================

def update_data_health(
    symbol: str,
    data_fetch_status: Dict,
    health_score: float
) -> Optional[Dict]:
    """Update or create data health record"""
    supabase = get_supabase()
    if not supabase:
        return None
    
    try:
        # Convert numpy/pandas types to JSON-serializable types
        serializable_status = _make_json_serializable(data_fetch_status)
        
        payload = {
            "symbol": symbol.upper(),
            "data_fetch_status": serializable_status,
            "health_score": float(health_score),  # Ensure it's a Python float
            "last_updated": datetime.now().isoformat()
        }
        
        # Upsert (update if exists, insert if not)
        # Note: If table doesn't exist, this will fail gracefully
        result = supabase.table("data_health").upsert(payload).execute()
        return result.data[0] if result.data else None
    except Exception as e:
        # If table doesn't exist, silently fail (as user mentioned it's not created)
        if "relation" in str(e).lower() or "does not exist" in str(e).lower():
            print(f"Warning: data_health table does not exist. Skipping save.")
            return None
        print(f"Error updating data health: {e}")
        return None


def get_data_health(symbol: Optional[str] = None) -> List[Dict]:
    """Get data health records"""
    supabase = get_supabase()
    if not supabase:
        return []
    
    try:
        query = supabase.table("data_health").select("*")
        
        if symbol:
            query = query.eq("symbol", symbol.upper())
        
        result = query.execute()
        return result.data if result.data else []
    except Exception as e:
        print(f"Error getting data health: {e}")
        return []

